export const LEAD_STATUSES = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  INTERESTED: 'INTERESTED',
  READY_TO_REGISTER: 'READY_TO_REGISTER',
  REGISTERED: 'REGISTERED',
  CUSTOMER: 'CUSTOMER',
  LOST: 'LOST',
};

export const LEAD_TEMPERATURES = {
  HOT: 'HOT',
  WARM: 'WARM',
  COLD: 'COLD',
};

export const CONVERSATION_STATES = {
  AI_ACTIVE: 'AI_ACTIVE',
  WAITING_FOR_CUSTOMER: 'WAITING_FOR_CUSTOMER',
  HUMAN_REQUIRED: 'HUMAN_REQUIRED',
  HUMAN_ACTIVE: 'HUMAN_ACTIVE',
  RESOLVED: 'RESOLVED',
  ARCHIVED: 'ARCHIVED',
};

export const SENDER_TYPES = {
  CUSTOMER: 'CUSTOMER',
  AI: 'AI',
  AGENT: 'AGENT',
  SYSTEM: 'SYSTEM',
};

export const USER_ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  AGENT: 'AGENT',
};